openapi: "3.0.1"
info:
  title: "Gatekeeper API"
  version: "2022-05-31T08:49:03Z"
servers:
  - url: "https://gatekeeper-api.civic.finance/"
paths:
  /v1/token/{chain}:
    post:
      responses:
        '202':
          description: Token creation accepted
      parameters:
        - name: "chain"
          in: "path"
          required: true
          schema:
            type: string
            enum:
              - solana
              - casper
              - ethereum
        - name: "gatekeeperNetwork"
            in: "query"
            required: true
            schema:
              type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ocivaApiGaCJI7eDYNHDdp"
        required: true
  /v1/token/{chain}/{walletAddress}:
    get:
      responses:
        '404':
          description: Token not found
        '200':
          description: Get token response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getTokenResponse"
      parameters:
        - name: "chain"
          in: "path"
          required: true
          schema:
            type: string
            enum:
              - solana
              - casper
              - ethereum
        - name: "walletAddress"
          in: "path"
          required: true
          schema:
            type: string
        - name: "gatekeeperNetwork"
          in: "query"
          required: true
          schema:
            type: string
    head:
      responses:
        '200':
          description: Get Token Response
      parameters:
        - name: "chain"
          in: "path"
          required: true
          schema:
            type: string
            enum:
              - solana
              - casper
              - ethereum
        - name: "walletAddress"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "gatekeeperNetwork"
          in: "query"
          required: true
          schema:
            type: string
    patch:
      responses:
        '200':
          description: Token creation response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/refreshTokenResponse"
      parameters:
        - name: "chain"
          in: "path"
          required: true
          schema:
            type: string
            enum:
              - solana
              - casper
              - ethereum
        - name: "walletAddress"
          in: "path"
          required: true
          schema:
            type: "string"
        - name: "gatekeeperNetwork"
          in: "query"
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ocivaApiGaQYWfLRJ770Ax"
        required: true
components:
  schemas:
    ocivaApiGaCJI7eDYNHDdp:
      type: "object"
      properties:
        address:
          type: "string"
        acceptedTermsAndConditionsLink:
          type: "string"
        ownerSigns:
          type: "boolean"
          default: false
        captchaToken:
          type: "string"
        identityAuthToken:
          type: "string"
        civicPassAuthToken:
          type: "string"
        provider:
          type: "string"
          enum:
            - "sip"
            - "faceIdentity"
            - "recaptcha"
            - "hcaptcha"
            - "web"
            - "faceUniqueness"
        name:
          type: "string"
        presentationRequestId:
          type: "string"
        acceptedDeclaration:
          type: "string"
        recaptchaToken:
          type: "string"
        acceptedBiometricsPolicyLink:
          type: "string"
        proof:
          type: "string"
    ocivaApiGaQYWfLRJ770Ax:
      type: "object"
      properties:
        request:
          type: "string"
        recaptchaToken:
          type: "string"
        ownerSigns:
          type: "boolean"
          default: false
        proof:
          type: "string"
        captchaToken:
          type: "string"
        identityAuthToken:
          type: "string"
    getTokenResponse:
      type: object
      properties:
        chain:
          type: object
          properties:
            type:
              type: string
            network:
              type: string
        gatekeeperNetwork:
          type: string
        walletAddress:
          type: string
        events:
          type: array
          items:
            type: object
            properties:
              eventType:
                type: string
              chain:
                type: object
                properties:
                  type:
                    type: string
                  network:
                    type: string
              gatekeeperNetwork:
                type: string
              timestamp:
                type: integer
                format: int32
              transaction:
                type: object
                properties:
                  _id:
                    type: string
              updatedRecord:
                type: object
                properties:
                  token:
                    type: string
                  walletAddress:
                    type: string
                  unconfirmedIssueTimestamp:
                    type: integer
                    format: int32
        token:
          type: string
        id:
          type: string
    refreshTokenResponse:
      type: object
      properties:
        status:
          type: string
          enum:
            - ok
