openapi: 3.0.3
info:
  title: Civic Pass Customer API
  description: |-
    The APIs described bellow enables Civic customers to issue and manage the Civic Pass for their dApp. To learn more about Civic Passes and their fundamentals please refer to the main [documentation](https://docs.civic.com/).
    
    # Terminology
    
    In the Customer API, the term `chain` refers to a blockchain programming model and the term `chainNetwork` to a network of the chain. For example, a "Layer 2" network like Polygon, which is using the ethereum (EVM) programming model is represented by `/pass/ethereum/polygon`.

  termsOfService: https://www.civic.com/legal/terms-of-service-civic-pass-v1/
  contact:
    name: Civic
    url: https://docs.civic.com
    email: devsupportp@civic.com
  version: 0.1.0
servers:
  - url: https://api.civic.com/partner
paths:
  /pass:
    post:
      tags:
        - pass
      summary: List all Civic Passes associated with your account
      operationId: listPass
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                limit:
                  type: number
                  default: 10
                skip:
                  type: number
                  default: 0
                filter:
                  type: object
                  properties:
                    state:
                      $ref: '#/components/schemas/State' 
                  required:
                    - state
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: object
      security:
        - pass_auth:
          - write:token
          - read:token
  /pass/{chain}/{chainNetwork}:
    post:
      tags:
        - pass
      summary: Issue a new Civic Pass to a wallet
      description: Triggers the issuance of a Civic Pass to a user's wallet.
      operationId: issuePass
      parameters:
        - name: chain
          in: path
          description: The type of blockchain that the Civic Pass was issued on.
          required: true
          example: solana
          schema:
            $ref: '#/components/schemas/Chain'
        - name: chainNetwork
          in: path
          description: The blockchain network
          required: true
          explode: true
          example: devnet
          schema:
            $ref: '#/components/schemas/ChainNetwork'
      requestBody:
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Wallet'   
        required: true
      responses:
        '202':
          description: Civic Pass issuance initiated
        '401':
          description: Unauthorized
        '400':
          description: Client error
      security:
        - pass_auth:
          - write:token
          - read:token
  /pass/{chain}/{chainNetwork}/{wallet}:
    get: 
      tags:
        - pass
      summary: Retrieve the Civic Pass associated with a wallet.
      operationId: getPass
      parameters:
        - name: chain
          in: path
          description: The blockchain type that the Civic Pass was issued on.
          required: true
          example: solana
          schema:
            $ref: '#/components/schemas/Chain'
        - name: wallet
          in: path
          description: The user's wallet the Civic Pass was issued to.
          required: true
          example: HV4xSMQq4gDUKU1DQGfGmMdmFJd69zmvkaRwLZogpgwi
          schema:
            type: string
        - name: chainNetwork
          in: path
          description: The blockchain network
          required: true
          explode: true
          example: devnet
          schema:
            $ref: '#/components/schemas/ChainNetwork'
      responses:
        '200':
            description: The Civic Pass associated with the given wallet.
        '404':
            description: No Civic pass is associatied with the given wallet.
      security:
        - pass_auth:
          - write:token
          - read:token
    patch: 
      tags:
        - pass
      summary: Update the Civic Pass associated with a wallet
      operationId: patchPass
      parameters:
        - name: chain
          in: path
          description: The blockchain type that the Civic Pass was issued on.
          required: true
          example: solana
          schema:
            $ref: '#/components/schemas/Chain'
        - name: wallet
          in: path
          description: The user's wallet the Civic Pass was issued to.
          required: true
          example: HV4xSMQq4gDUKU1DQGfGmMdmFJd69zmvkaRwLZogpgwi
          schema:
            type: string
        - name: chainNetwork
          in: path
          description: The blockchain network
          required: true
          explode: true
          example: devnet
          schema:
            $ref: '#/components/schemas/ChainNetwork'
      requestBody:
        content:
          application/json:
            schema: 
             $ref: '#/components/schemas/UpdateState'
        required: true
      responses:
        '200':
            description: The list of Civic Passes associated with this wallet.
      security:
        - pass_auth:
          - write:token
          - read:token
    delete:
      tags:
        - pass
      summary: Revoke the Civic Pass associated with a wallet
      operationId: deletePass
      description: Revoking a Civic Pass is **irreversible**. After the Civic Pass has been revoked, it is not possible to issue a new Civic Pass to the same {chain, wallet, network} combination.
      parameters:
        - name: chain
          in: path
          description: The blockchain type that the Civic Pass was issued on.
          required: true
          example: solana
          schema:
            $ref: '#/components/schemas/Chain'
        - name: wallet
          in: path
          description: The user's wallet the Civic Pass was issued to.
          required: true
          example: HV4xSMQq4gDUKU1DQGfGmMdmFJd69zmvkaRwLZogpgwi
          schema:
            type: string
        - name: chainNetwork
          in: path
          description: The blockchain network
          required: true
          explode: true
          example: devnet
          schema:
            $ref: '#/components/schemas/ChainNetwork'
      responses:
        '200':
            description: The list of Civic Passes associated with this wallet.
      security:
        - pass_auth:
          - write:token
          - read:token
tags:
  - name: pass
    description: Issue and manage Civic Passes
components:
  schemas:
    Wallet:
      type: object
      properties: 
        walletAddress:
          type: string
          example: "0xeF3D8ce560e72a79A6baD55619B3f1E06A69F5E3"
    ChainNetwork:
      type: string
      description: The chain network 
      enum:
        - devnet
        - mainnet
        - goerli
    Chain:
      type: string
      description: The chain type
      enum:
        - solana
        - ethereum
        - casper
    State:
      type: string
      description: Available status
      enum:
        - ACTIVE
        - REVOKED
        - FROZEN
        - REJECTED
    UpdateState:
      type: object
      properties:
        state:
          $ref: '#/components/schemas/State'
        expiryTimestamp:
          description: The new expiration timestamp
          type: number
  securitySchemes:
    pass_auth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://dev-x4psl5y0zb6ue6dl.us.auth0.com/oauth/token
          scopes: {}
