import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
// Generated by `pnpm gen-api-docs` into docs/bryn/api/ (git-ignored build
// artifact). Default export is the array of API sidebar items.
import brynApiSidebar from '../docs/bryn/api/sidebar';

type SidebarItemConfig = Extract<SidebarsConfig[string], readonly unknown[]>[number];

// See sidebars/civic.ts: top-level groups are always-open section headers.
const TOP_GROUP = { collapsible: false as const, collapsed: false as const };

const sidebar: SidebarItemConfig[] = [
  { type: 'doc', id: 'bryn/index', label: 'Overview' },
  { type: 'doc', id: 'bryn/mcp', label: 'MCP Server' },
  { type: 'doc', id: 'bryn/frontend-recipes', label: 'Personalization Recipes' },
  // A static section header like the other top-level groups: this site's swizzled sidebar
  // treats top-level categories as non-collapsible headers, so a collapsed top-level category
  // renders but won't expand. Keeping it open leaves the "Signing requests" child link visible
  // and clickable. Placed above the always-expanded Control Plane API list so it stays in view.
  {
    type: 'category',
    label: 'Advanced',
    ...TOP_GROUP,
    items: [{ type: 'doc', id: 'bryn/signing', label: 'Signing requests' }],
  },
  {
    type: 'category',
    label: 'Control Plane API',
    ...TOP_GROUP,
    items: brynApiSidebar as SidebarItemConfig[],
  },
];

export default sidebar;
