name: Link Check (Production)

on:
  push:
    branches: [main]
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Link Checker (Deployed Site)
        uses: lycheeverse/lychee-action@v2
        with:
          # Check against deployed site using base URL
          args: >
            --config lychee.toml
            --base-url 'https://docs.civic.com'
            --no-progress
            '**/*.md'
            '**/*.mdx'
          fail: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Issue From File
        if: failure()
        uses: peter-evans/create-issue-from-file@v5
        with:
          title: 'Link Checker Report: Broken Links Found'
          content-filepath: ./lychee/out.md
          labels: |
            documentation
            automated